config/routes.rb
Ecogranja::Application.routes.draw do
  root :to => "home#index"
  
  match "login",  :to => "sessions#login_attempt"
  match "logout", :to => "sessions#logout"
  
  match '/home/agropedia'         => 'home#agropedia'
  match '/home/learning'          => 'home#learning'
  match '/home/farmsadmin'        => 'home#farmsadmin'
  match '/home/administration'    => 'home#administration'
  match '/home/decisionmaking'    => 'home#decisionmaking'
  match '/sessions/login_attempt' => 'sessions#login_attempt'
  match '/sessions/logout'        => 'sessions#logout'
  match '/articles/admin'         => 'articles#admin'
  match '/crops/admin'            => 'crops#admin'  
  
  resources :home, :users, :profiles, :sessions, :farms, :coordinates, :crops, :productions, :environments, :soil_improvements, :scenarios, :articles, :categories, :simulations 
  
  

end

app/models/farm.rb
class Farm < ActiveRecord::Base
  attr_accessible   :name, 
                    :owner, 
                    :address, 
                    :city,
                    :state,
                    :country,
                    :loc_lat, 
                    :loc_lng,
                    :loc_alt, 
                    :area,
                    :avg_slope,
                    :user_id
                    
  validates :name,      :presence => true
  validates :owner,     :presence => true
  validates :address,   :presence => true
  validates :city,      :presence => true
  validates :state,     :presence => true
  validates :country,   :presence => true
  validates :loc_lat,   :presence => true
  validates :loc_lng,   :presence => true
  validates :loc_alt,   :presence => true
  validates :area,      :presence => true
  validates :avg_slope, :presence => true
  validates :user_id,   :presence => true
  
  has_many :coordinates, :dependent => :destroy
  has_many :environments, :dependent => :destroy
  has_many :productions, :dependent => :destroy
  has_many :soil_improvements, :dependent => :destroy  
  has_many :scenarios, :dependent => :destroy
  accepts_nested_attributes_for :coordinates
  
  belongs_to :user
end

app/controllers/farms_controller.rb
class FarmsController < ApplicationController
    
  def index
    unless @mode == 'public'
      @farm  = Farm.new
      for i in 0..2
        @farm.coordinates[i] = Coordinate.new(:ind => i, :farm_id => @farm.id)
      end
      if @mode == 'normal'
        @user  = User.find(@current_user.id)
        @farms = Farm.where("user_id = '?'", @current_user.id)
      elsif @mode == 'admin'
        @farms = Farm.order('name')
        @users = User.order('username')
      end
    end
    respond_to do |format|
      flash[:notice] = 'Administraci&oacute;n de Granjas'
      flash[:success] = true
      format.html
    end
  end

  def create
    coordinates = params[:farm][:coordinates_attributes]
    params[:farm].delete :coordinates_attributes
    @farm = Farm.new(params[:farm])
    if @mode == 'normal'
      @user  = User.find(@farm.user_id)
      @farms = Farm.where("user_id = '?'", @current_user.id)
    elsif @mode == 'admin'
      @users = User.order('username')
      @farms = Farm.order('name')
    end
    respond_to do |format|
      if @farm.save
        coordinates.each do |coord|
          coord[1].merge!(:farm_id => @farm.id)
          coordinate = Coordinate.new(coord[1])
          coordinate.save
        end
        flash[:notice] = 'La Granja ha sido registrada satisfactoriamente.'
        flash[:success] = true
        format.js {
          render :partial => 'refresh'
        }         
      else
        flash[:notice] = 'La Granja no ha sido registrada.'
        flash[:success] = false
        format.js {
          render :partial => 'refresh'
        } 
      end
    end
  end

  def edit
    @farm = Farm.find(params[:id])    
    if @mode == 'normal'
      @user  = User.find(@farm.user_id)
    elsif @mode == 'admin'
      @users = User.order('username')
    end
    respond_to do |format|
        flash[:notice] = 'Edici&oacute;n de la Granja: '+@farm.name+'.'
        flash[:success] = true
        format.js {
          render :partial => 'refresh'
        }  
    end    
  end
  
  def update
    coordinates = params[:farm][:coordinates_attributes]
    params[:farm].delete :coordinates_attributes
    @farm = Farm.find(params[:id])
    if @mode == 'normal'
      @user  = User.find(@farm.user_id)
      @farms = Farm.where("user_id = '?'", @farm.user_id)
    elsif @mode == 'admin'
      @users = User.order('username')
      @farms = Farm.order('name')
    end
    respond_to do |format|
      if @farm.update_attributes(params[:farm])
        # if @farm.coordinates.count == coordinates.count
        #   coordinates.each_with_index do {|coord, i|}
        #     coord[1].merge!(:farm_id => @farm.id)
        #     @farm.coordinates[i].update_attributes(coord[1])
        #     @farm.coordinates[i].save
        #   end
        # elsif @farm.coordinates.count > coordinates.count
        # 
        # elsif @farm.coordinates.count < coordinates.count      
        #
        # end
        flash[:notice] = 'La Granja ha sido actualizada satisfactoriamente.'
        flash[:success] = true
        format.js {
          render :partial => 'refresh'
        }
      else
        format.js {
          flash[:notice] = 'La Granja no ha sido actualizada'
          flash[:success] = false
          render :partial => 'refresh'
        }     
      end
    end
  end
  
  def destroy
    @farm = Farm.find(params[:id])
    @user  = User.find(@current_user.id)
    if @mode == 'normal'
      @farms = Farm.where("user_id = '?'", @current_user.id)
    elsif @mode == 'admin'
      @farms = Farm.order('name')
      @users = User.order('username')
    end
    
    respond_to do |format|
      if @farm.destroy
        flash[:notice] = 'La granja fue eliminada satisfactoriamente'
        flash[:success] = true
        format.js { 
          render :partial => 'refresh'
        }
      else
        flash[:notice] = 'La granja no fue eliminada'
        flash[:success] = false
        format.js { 
          render :partial => 'refresh'
        }
      end
    end
  end
  
end

app/helpers/farms_helper.rb
module FarmsHelper
end

app/views/farms/_farms.html.erb
<table id="tablaGranjas">
<thead>
<tr>
  <th>Nombre</th>
  <th>Usuario</th>
  <th>Propietario</th>
  <th>Dirección</th>
  <th>Ciudad/Pueblo</th>
  <th>Departamento/Estado</th>
  <th>País</th>
  <th>Latitud promedio</th>
  <th>Longitud promedio</th>
  <th>Altitud promedio</th>
  <th>Área</th>
  <th>Editar</th>
  <th>Eliminar</th>
</tr>
</thead>
<tbody>
	<% @farms.each do |farm| %>
	<tr>
	  <td><b><%= farm.name %></b> </td>
	  <td>	 <%= farm.user.username %></td>
	  <td>	 <%= farm.owner %></td>
	  <td>	 <%= farm.address %></td>
	  <td>	 <%= farm.city %></td>
	  <td>	 <%= farm.state %></td>
	  <td>	 <%= farm.country %></td>
	  <td>	 <%= farm.loc_lat %></td>
	  <td>	 <%= farm.loc_lng %></td>
	  <td>	 <%= farm.loc_alt %></td>
	  <td>	 <%= farm.area %></td>
	  <td><%= button_to 'Editar', edit_farm_path(farm), :method => :get, :remote => 'true', :class => 'button' %></td>
	  <td><%= button_to 'Eliminar', farm, :method => :delete, :remote => 'true', :class => 'button' %></td>
	</tr>
	<% end %>
</tbody>
</table>
 
<br />
<%= link_to 'Nueva Granja', { :controller => "farms", :action => "index"}, :class => "button" %>

app/views/farms/_form.html.erb
<%= form_for(@farm, :remote => 'true') do |f| %>
	<div class="field">
		<%= f.label :name, "Nombre de la Granja" %><br />
		<%= f.text_field :name, :title => "Razón social de la Granja" %>
	</div>
	<div class="field">
	    <%= f.label :owner, "Propietario" %><br />
	    <%= f.text_field :owner, :title => "Nombre de la persona juridica o natural dueña de la granja" %>
    </div>
    <% if @mode == 'normal' %>
    	<%= f.hidden_field :user_id, :value => @user.id %>
    <% elsif @mode == 'admin' %>
	    <div class="field">
	    	<%= f.label :user_id, "Usuario" %><br />
	    	<%= f.select :user_id, @users.collect {|c| [ c.username, c.id ]}, :title => 'Seleccionar un usuario' %>
	    </div>
    <% end %>
    <div class="field">
    	<%= f.label :address, "Dirección" %><br />
    	<%= f.text_field :address, :title => 'Dirección de la Granja' %>
    </div>
    <div class="field">
    	<%= f.label :city, "Ciudad/Pueblo" %><br />
    	<%= f.text_field :city, :title => 'Ciudad o pueblo donde se ubica la Granja' %>
    </div>
    <div class="field">
    	<%= f.label :state, "Departamento/Estado" %><br />
    	<%= f.text_field :state, :title => 'Departamento o estado donde se ubica la Granja' %>
    </div>
    <div class="field">
    	<%= f.label :country, "País" %><br />
    	<%= f.text_field :country, :title => 'País donde se ubica la Granja' %>
    </div>
    <br />
    <br />
    <h3><span></span>Datos geograficos</h3>
    <br />
    <div id='viewer_container'>
		<div id='viewer_maps'>    	
			<div id='google_maps'>
			</div>
			<div id="viewer_canvas">
				<canvas id="canvas">
					Su navegador web no soporta el elemento Canvas (HTML5).
				</canvas>
			</div>
		</div>
		<div id='viewer_controls'>
			<button id='setGeoData' class='button'>Asignar datos geograficos</button>
			<button id='resize' class='button'>Resize</button>
		</div>
	</div>
	<br />
    <div class="field">
    	<%= f.label :area, "Área" %><br />
    	<%= f.text_field :area, :title => 'Área aproximada de la Granja <br />metros cuadrados [m²]' %>
    </div>
    <div class="field">
    	<%= f.label :loc_lat, 'Latitud promedio' %><br />
    	<%= f.text_field :loc_lat, :title => 'Latitud promedio del área seleccionada' %>
    </div>
    <div class="field">
    	<%= f.label :loc_lng, "Longitud promedio" %><br />
    	<%= f.text_field :loc_lng, :title => 'Longitud promedio del área seleccionada' %>
    </div>
    <div class="field">
    	<%= f.label :loc_alt, "Altitud promedio" %><br />
    	<%= f.text_field :loc_alt, :title => 'Altitud promedio del área seleccionada' %>
    </div>
    <div class="field">
    	<%= f.label :avg_slope, "Pendiente promedio" %><br />
    	<%= f.text_field :avg_slope, :title => 'Pendiente promedio del área seleccionada' %>
    </div>
    <%= f.fields_for :coordinates, @farm.coordinates do |coord| %>
	    <fieldset>
	    	<legend>Coordenada <%= (coord.object.ind + 1) %> </legend>
	    	<%= coord.hidden_field :ind %>
		    <div class="cell">
		    	<%= coord.label :lat, "Latitud" %><br />
		    	<%= coord.text_field :lat, :title => 'Latitud de la coordenada '+(coord.object.ind + 1).to_s %>
		    </div>
		    <div class="cell">
		    	<%= coord.label :lng, "Longitud" %><br />
		    	<%= coord.text_field :lng, :title => 'Longitud de la coordenada '+(coord.object.ind + 1).to_s %>
		    </div>
		    <div class="cell">
		    	<%= coord.label :alt, "Altitud" %><br />
		    	<%= coord.text_field :alt, :title => 'Altitud de la coordenada '+(coord.object.ind + 1).to_s %>
		    </div>
	    </fieldset>
    <% end %>
    
	<div class="actions">
		<%= f.submit 'Registrar Granja', :class => 'button'%>
	</div>
<% end %>

app/views/farms/_refresh.js.erb
<% if flash[:success] == true %>
	<% unless @current_action == 'index'%>
		<% if @current_action == 'edit'%>
			$('#farm').html("<%= escape_javascript(render :partial => 'form') %>");
		<% elsif @current_action == 'update' %>
			clear_form_elements($('#farm > form')[0]);
			$('#farms').html("<%= escape_javascript(render :partial => 'farms') %>");
		<% end %>
			main_farms();
	<% else %>
		$('#navigation').html("<%= escape_javascript(render :partial => "layouts/menu") %>");
		$('#navigation a').on('click', function() {
			ajaxContentRedirect(this.href);
			return false;
		});
		$('#menutd > li > a:first').unbind('click');
	<% end %>
<% end %>

$('html, body').animate({scrollTop:0}, 'slow');
$('#notice').html('<%= flash[:notice].html_safe %>');
$('#notice').slideDown("fast").delay(2500).fadeOut("slow");
<% flash[:notice] = nil %>

app/views/farms/index.html.erb
<% unless @mode == 'public' %>
	<% if @farm.errors.any? %>
		<div id="error_explanation">
			<h2> <%= pluralize(@farm.errors.count, "error")%>, posibles causas:</h2>
			<ul>
				<% @farm.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>		
			</ul>	
		</div>
	<% end %>
	
	<h3><span></span>Granja</h3>
	<br/>
	<div id="farm">	
		<%= render :partial => "form" %>
	</div>

	<div class="separator"></div>
	
	<h3><span></span> Listado de granjas</h3>
	<br/>
	<div id="farms">	
		<%= render :partial => "farms" %>
	</div>
<% end %>

<div class="cleaner"></div>

<% unless @mode == 'public' %>
	<script src="http://maps.google.com/maps/api/js?sensor=false&callback=isNaN"
	  type="text/javascript">
	</script>
	
	<script type="text/javascript">
		
		window.google = window.google || {};
		google.maps = google.maps || {};
		
		function complete_jquery_data_tables_farms(data, textStatus, jqxhr){
			if(textStatus == 'success'){
				libraries['jquery_data_tables']	=true;
				ready_jquery_data_tables('tablaGranjas');
			}
		};	
		
		function complete_poo(data, textStatus, jqxhr){
			if(textStatus == 'success'){
				libraries['poo']		=true;
				ready_poo();
			}
		};
		
		function ready_poo(){
			if(!libraries['viewer']){
				$.getScript("/assets/visualizador/viewer.js", complete_viewer);
			}
			else{
				ready_viewer();
			}
		};
		
		function complete_viewer(data, textStatus, jqxhr){
			if(textStatus == 'success'){
				libraries['viewer']		=true;
				ready_viewer();
			}
		};
		
		function ready_viewer(){
			if(!libraries['google_maps']){
				loadGoogleMaps();
			}
			else{
				initializeMap();
			}
		};
		
		function loadGoogleMaps() {
		  (function() {
			  function getScript(src) {
			    var s = document.createElement('script');
			    s.src = src;
			    document.body.appendChild(s);
			  };
		  })();
		  libraries['google_maps'] = true;
		  initializeMap();
		  ready_google_maps();
		};
		
		function ready_google_maps(){
			$("#setGeoData").click(function() {
	        	setCoordinates({area:	 	'farm_area',
	        					loc_lat: 	'farm_loc_lat', 
	        					loc_lng: 	'farm_loc_lng', 
	        					loc_alt: 	'farm_loc_alt',
	        					avg_slope:	'farm_avg_slope',
	        					coord:		'farm_coordinates_attributes',
	        					coord_count: locations.length });
	        	return false;
	   		});
		};
		
		function main_farms(){
			if(!libraries['jquery_ui']){
				$.getScript("/assets/jquery/jquery-ui-1.8.23.custom.min.js", complete_jquery_ui);
			}
			else{
				ready_jquery_ui();
			}
			if(!libraries['jquery_data_tables']){
				$.getScript("/assets/jquery/jquery.dataTables.min.js", complete_jquery_data_tables_farms);
			}
			else{
				ready_jquery_data_tables('tablaGranjas');
			}
			if(!libraries['jquery_tools']){
				$.getScript("/assets/jquery/jquery.tools.min.js", complete_jquery_tools);
			}
			else{
				ready_jquery_tools();
			}
			if(!libraries['google_maps']){
				if(!libraries['poo']){
					$.getScript("/assets/poo.js", complete_poo);
				}
				else{
					ready_poo();
				}
			}
			else{
				initializeMap();
			}
		};
		
		$(document).ready(function () {
			if(!libraries['google_maps']){
				main_farms();
				<%= render :file => "farms/_refresh.js.erb" %>
			}
		});
	</script> 
<% end %>