config/routes.rb
Ecogranja::Application.routes.draw do
  root :to => "home#index"
  
  match "login",  :to => "sessions#login_attempt"
  match "logout", :to => "sessions#logout"
  
  match '/home/agropedia'         => 'home#agropedia'
  match '/home/learning'          => 'home#learning'
  match '/home/farmsadmin'        => 'home#farmsadmin'
  match '/home/administration'    => 'home#administration'
  match '/home/decisionmaking'    => 'home#decisionmaking'
  match '/sessions/login_attempt' => 'sessions#login_attempt'
  match '/sessions/logout'        => 'sessions#logout'
  match '/articles/admin'         => 'articles#admin'
  match '/crops/admin'            => 'crops#admin'  
  
  resources :home, :users, :profiles, :sessions, :farms, :coordinates, :crops, :productions, :environments, :soil_improvements, :scenarios, :articles, :categories, :simulations 
  
  

end

app/models/crop.rb
class Crop < ActiveRecord::Base
  attr_accessible :name,
                  :description,
                  :NabsorPro,
                  :PAbsorPro,
                  :KAbsorPro,
                  :NExtraPro,
                  :PExtraPro,
                  :KExtraPro,
                  :ProPhPlantas,
                  :DesPhPlantas,
                  :PesoUniCultivo,
                  :DesPesoUniCul,
                  :PesoUniCosecha,
                  :DesPesoUniCos,
                  :TiemVegetativo,
                  :TiemReproductivo,
                  :ProLumiPlanta,
                  :DesLumiPlanta,
                  :ProPreciPlanta,
                  :DesPreciPlanta,
                  :ProHumePlanta,
                  :DesHumePlanta,
                  :ProTempPlanta,
                  :DesTempPlanta,
                  :article_id
                  
  validates :name,            :presence => true
  validates :description,     :presence => true
  validates :NabsorPro,       :presence => true
  validates :PAbsorPro,       :presence => true
  validates :KAbsorPro,       :presence => true
  validates :NExtraPro,       :presence => true
  validates :PExtraPro,       :presence => true
  validates :KExtraPro,       :presence => true
  validates :ProPhPlantas,    :presence => true
  validates :DesPhPlantas,    :presence => true
  validates :PesoUniCultivo,  :presence => true
  validates :DesPesoUniCul,   :presence => true
  validates :PesoUniCosecha,  :presence => true
  validates :DesPesoUniCos,   :presence => true
  validates :TiemVegetativo,  :presence => true
  validates :TiemReproductivo,:presence => true
  validates :ProLumiPlanta,   :presence => true
  validates :DesLumiPlanta,   :presence => true
  validates :ProPreciPlanta,  :presence => true
  validates :DesPreciPlanta,  :presence => true
  validates :ProHumePlanta,   :presence => true
  validates :DesHumePlanta,   :presence => true
  validates :ProTempPlanta,   :presence => true
  validates :DesTempPlanta,   :presence => true
  validates :article_id,      :presence => true
  
  has_many   :scenarios, :dependent => :destroy
  belongs_to :article
end

app/controllers/crops_controller.rb
class CropsController < ApplicationController
  
  def index
    @crop     = Crop.find(:first, :offset =>rand(Crop.count))
    @crops    = Crop.order('name')
    @articles = Article.order('title')
    respond_to do |format|
      flash[:notice] = 'Administraci&oacute;n de Cultivos'
      flash[:success] = true
      format.html
    end
  end
  
  def admin
    if @mode == 'admin'
      @crop     = Crop.new
      @crops    = Crop.order('name')
      @articles = Article.order('title')
    end
    respond_to do |format|
      flash[:notice] = 'Administraci&oacute;n de Cultivos'
      flash[:success] = true
      format.html
    end
  end
  
  def create
    if @mode == 'admin'
      @crop     = Crop.new(params[:crop])
      @crops    = Crop.order('name')
      @articles = Article.order('title')
    end
    respond_to do |format|
      if @crop.save
        flash[:notice] = 'El cultivo ha sido registrado satisfactoriamente.'
        flash[:success] = true
        format.js {
          render :partial => 'refresh'
        }
      else
        flash[:notice] = 'El cultivo no ha sido registrado.'
        flash[:success] = false
        format.js {
          render :partial => 'refresh'
        } 
      end
    end
  end
  
  def show
    @crop     = Crop.new
    @crops    = Crop.order('name')
    respond_to do |format|
        flash[:notice] = 'Cultivo: '+@crop.name
        flash[:success] = true
        format.js {
          render :partial => 'refresh'
        }
    end
  end
  
  def edit
    if @mode == 'admin'
      @crop     = Crop.find(params[:id])
      @crops    = Crop.order('name')
      @articles = Article.order('title')
    end
    respond_to do |format|
        flash[:notice] = 'Edici&oacute;n del cultivo: '+@crop.name+'.'
        flash[:success] = true
        format.html{
          render :action => "admin" 
        }
        format.js {
          render :partial => 'refresh'
        } 
    end    
  end
  
  def update
    if @mode == 'admin'
      @crop     = Crop.find(params[:id])
      @crops    = Crop.order('name')
      @articles = Article.order('title')
    end
    respond_to do |format|
      if @crop.update_attributes(params[:crop])
        flash[:notice] = 'El cultivo ha sido actualizado satisfactoriamente'
        flash[:success] = true
        format.js {
          render :partial => 'refresh'
        }
      else
        flash[:notice] = 'El cultivo no ha sido actualizado'
        flash[:success] = false
        format.js {
          render :partial => 'refresh'
        }
      end
    end
  end
  
  def destroy
    if @mode == 'admin'
      @crop     = Crop.find(params[:id])
      @crops    = Crop.order('name')
      @articles = Article.order('title')
    end
    respond_to do |format|
      if @crop.destroy
        flash[:notice] = 'El cultivo fue eliminado satisfactoriamente'
        flash[:success] = true
        format.js { 
          render :partial => 'refresh'
        }
      else
        flash[:notice] = 'El cultivo no fue eliminado'
        flash[:success] = false
        format.js { 
          render :partial => 'refresh'
        }
      end
    end
  end
  
end

app/helpers/crops_helper.rb
module CropsHelper
end

app/views/crops/_crop.html.erb
<% unless @crop.nil? %>
	<table id="tablaCultivo">
	<thead>
	<tr>
		</tr>
			<th>Propiedad</th>
			<th>Valor</th>
		<tr>
	  
	</tr>
	</thead>
	<tbody>	
		<tr>
		  	  <td><b>Articulo</b></td>
			  <td><b><%= @crop.article.title %></b></td>
		</tr>
		<tr>
			  <td><b>Nombre del cultivo</b></td>
			  <td>	 <%= @crop.name %></td>
		</tr>
		<tr>	  
			  <td><b>Descripción del cultivo</b></td>
			  <td>	 <%= @crop.description %></td>
		</tr>
		<tr>	  
			  <td><b>Nitrogeno absorbido</b></td>
			  <td>	 <%= @crop.NabsorPro %></td>
		</tr>
		<tr>	  
			  <td><b>Fósforo absorbido</b></td>
			  <td>	 <%= @crop.PAbsorPro %></td>
		</tr>
		<tr>	  
			  <td><b>Potasio absorbido</b></td>
			  <td>	 <%= @crop.KAbsorPro %></td>
		</tr>
		<tr>	  
			  <td><b>Nitrógeno extraido</b></td>
			  <td>	 <%= @crop.NExtraPro %></td>
		</tr>
		<tr>	  
			  <td><b>Fósforo extraido</b></td>
			  <td>	 <%= @crop.PExtraPro %></td>
		</tr>
		<tr>	  
			  <td><b>Potasio extraido</b></td>
			  <td>	 <%= @crop.KExtraPro %></td>
		</tr>
		<tr>	  
			  <td><b>Promedio Ph </b></td>
			  <td>	 <%= @crop.ProPhPlantas %></td>
		</tr>
		<tr>	  
			  <td><b>Desviación estandar del Ph</b></td>
			  <td>	 <%= @crop.DesPhPlantas %></td>
		</tr>
		<tr>	  
			  <td><b>Peso seco de una planta</b></td>
			  <td>	 <%= @crop.PesoUniCultivo %></td>
		</tr>
		<tr>  
			  <td><b>Desviación estandar del peso seco de una planta</b></td>
			  <td>	 <%= @crop.DesPesoUniCul %></td>
		</tr>
		<tr>  
			  <td><b>Peso seco de la cosecha</b></td>
			  <td>	 <%= @crop.PesoUniCosecha %></td>
		</tr>
		<tr> 
			  <td><b>Desviación estandar del peso seco de la cosecha</b></td>
			  <td>	 <%= @crop.DesPesoUniCos %></td>
		</tr>
		<tr>  
			  <td><b>Tiempo de desarrollo</b></td>
			  <td>	 <%= @crop.TiemVegetativo %></td>
		</tr>
		<tr>	  
			  <td><b>Tiempo productivo</b></td>
			  <td>	 <%= @crop.TiemReproductivo %></td>
		</tr>
		<tr>	  
			  <td><b>Luminosidad promedio del cultivo</b></td>
			  <td>	 <%= @crop.ProLumiPlanta %></td>
		</tr>
		<tr>	  
			  <td><b>Desviación estandar de la Luminosidad</b></td>
			  <td>	 <%= @crop.DesLumiPlanta %></td>
		</tr>
		<tr>	  
			  <td><b>Precipitacion promedio del cultivo</b></td>
			  <td>	 <%= @crop.ProPreciPlanta %></td>
		</tr>
		<tr>	  
			  <td><b>Desviación estandar de la precipitacion</b></td>
			  <td>	 <%= @crop.DesPreciPlanta %></td>
		</tr>
		<tr>	  
			  <td><b>Humedad promedio del cultivo</b></td>
			  <td>	 <%= @crop.ProHumePlanta %></td>
		</tr>
		<tr>	  
			  <td><b>Desviación estandar de la Humedad</b></td>
			  <td>	 <%= @crop.DesHumePlanta %></td>
		</tr>
		<tr>	  
			  <td><b>Temperatura promedio del cultivo</b></td>
			  <td>	 <%= @crop.ProTempPlanta %></td>
		</tr>
		<tr>	  
			  <td><b>Desviación estandar de la Temperatura</b></td>
			  <td>	 <%= @crop.DesTempPlanta %></td>
		</tr>
	</tbody>
	</table>
<% end %>

app/views/crops/_crops.html.erb
<table id="tablaCultivos">
<thead>
<tr>
  <th>Articulo</th>
  <th>Nombre del cultivo</th>
  <th>Descripción del cultivo</th>
  <th>Nitrogeno absorbido</th>
  <th>Fósforo absorbido</th>
  <th>Potasio absorbido</th>
  <th>Nitrógeno extraido</th>
  <th>Fósforo extraido</th>
  <th>Potasio extraido</th>
  <th>Promedio Ph </th>
  <th>Desviación estandar del Ph</th>
  <th>Peso seco de una planta</th>
  <th>Desviación estandar del peso seco de una planta</th>
  <th>Peso seco de la cosecha</th>
  <th>Desviación estandar del peso seco de la cosecha</th>
  <th>Tiempo de desarrollo</th>
  <th>Tiempo productivo</th>
  <th>Luminosidad promedio del cultivo</th>
  <th>Desviación estandar de la Luminosidad</th>
  <th>Precipitacion promedio del cultivo</th>
  <th>Desviación estandar de la precipitacion</th>
  <th>Humedad promedio del cultivo</th>
  <th>Desviación estandar de la Humedad</th>
  <th>Temperatura promedio del cultivo</th>
  <th>Desviación estandar de la Temperatura</th>
  <th>Editar</th>
  <th>Eliminar</th>
</tr>
</thead>
<tbody>	
	<% @crops.each do |crop| %>
	<tr>
	  <td><b><%= crop.article.title %></b></td>
	  <td>	 <%= crop.name %></td>
	  <td>	 <%= crop.description %></td>
	  <td>	 <%= crop.NabsorPro %></td>
	  <td>	 <%= crop.PAbsorPro %></td>
	  <td>	 <%= crop.KAbsorPro %></td>
	  <td>	 <%= crop.NExtraPro %></td>
	  <td>	 <%= crop.PExtraPro %></td>
	  <td>	 <%= crop.KExtraPro %></td>
	  <td>	 <%= crop.ProPhPlantas %></td>
	  <td>	 <%= crop.DesPhPlantas %></td>
	  <td>	 <%= crop.PesoUniCultivo %></td>
	  <td>	 <%= crop.DesPesoUniCul %></td>
	  <td>	 <%= crop.PesoUniCosecha %></td>
	  <td>	 <%= crop.DesPesoUniCos %></td>
	  <td>	 <%= crop.TiemVegetativo %></td>
	  <td>	 <%= crop.TiemReproductivo %></td>
	  <td>	 <%= crop.ProLumiPlanta %></td>
	  <td>	 <%= crop.DesLumiPlanta %></td>
	  <td>	 <%= crop.ProPreciPlanta %></td>
	  <td>	 <%= crop.DesPreciPlanta %></td>
	  <td>	 <%= crop.ProHumePlanta %></td>
	  <td>	 <%= crop.DesHumePlanta %></td>
	  <td>	 <%= crop.ProTempPlanta %></td>
	  <td>	 <%= crop.DesTempPlanta %></td>
	  <td><%= link_to 'Editar', edit_crop_path(crop), :method => "get", :remote => true, :class => "button" %></td>
	  <td><%= button_to "Eliminar", crop, :method => :delete, :remote => true, :class => "button" %></td>
	  
	</tr>
	<% end %>
</tbody>
</table>

<br />
<%= link_to 'Nuevo cultivo', { :controller => "crops", :action => "index"}, :class => "button" %>

app/views/crops/_form.html.erb
<%= form_for(@crop, :remote => true) do |f| %>	
	<div class="field">
		<%= f.label :article_id, "Articulo" %><br />
		<%= f.select :article_id, @articles.collect {|c| [ c.title, c.id ]}, :title => 'Articulo que describe el cultivo' %>
	</div>
	<div class="field">
		<%= f.label :name, "Nombre del cultivo" %><br />
		<%= f.text_field :name, :title => 'Nombre del cultivo<br /> Tipo: alfanumérico <br /> Ej: Maiz.' %>
	</div>
	<div class="field">
		<%= f.label :description, "Descripción del cultivo" %><br />
		<%= f.text_field :description, :title => 'Descripción del cultivo<br /> Tipo: alfanumérico <br /> Ej: planta gramínea anual originaria de América.' %>
	</div>
	<div class="field">
		<%= f.label :NabsorPro, "Nitrogeno absorbido" %><br />
		<%= f.text_field :NabsorPro, :title => 'Nitrogeno necesario para el crecimiento del cultivo <br /> Tipo: numérico  <br /> Unidades: [Kg/tn] <br /> Ej: 22' %>
	</div>
	<div class="field">
		<%= f.label :PAbsorPro, "Fósforo absorbido" %><br />
		<%= f.text_field :PAbsorPro, :title => 'Fósforo necesario para el crecimiento del cultivo <br /> Tipo: numérico  <br /> Unidades: [Kg/tn] <br /> Ej: 4' %>
	</div>
	<div class="field">
		<%= f.label :KAbsorPro, "Potasio absorbido" %><br />
		<%= f.text_field :KAbsorPro, :title => 'Potasio necesario para el crecimiento del cultivo <br /> Tipo: numérico  <br /> Unidades: [Kg/tn] <br /> Ej: 19' %>
	</div>
	<div class="field">
		<%= f.label :NExtraPro, "Nitrógeno extraido" %><br />
		<%= f.text_field :NExtraPro, :title => 'Nitrógeno extraido para el crecimiento de la cosecha <br /> Tipo: numérico  <br /> Unidades: [Kg/tn] <br /> Ej: 15' %>
	</div>
	<div class="field">
		<%= f.label :PExtraPro, "Fósforo extraido" %><br />
		<%= f.text_field :PExtraPro, :title => 'Fósforo extraido para el crecimiento de la cosecha <br /> Tipo: numérico  <br /> Unidades: [Kg/tn] <br /> Ej: 3' %>
	</div>
	<div class="field">
		<%= f.label :KExtraPro, "Potasio extraido" %><br />
		<%= f.text_field :KExtraPro, :title => 'Potasio extraido para el crecimiento de la cosecha <br /> Tipo: numérico  <br /> Unidades: [Kg/tn] <br /> Ej: 4' %>
	</div>
	<div class="field">
		<%= f.label :ProPhPlantas, "Promedio Ph requerido por las plantas" %><br />
		<%= f.text_field :ProPhPlantas, :title => 'Medida del valor de Ph optimo para el desarrollo de la planta <br /> Tipo: numérico  <br /> Unidades: [ph] <br /> Ej: 6.5' %>
	</div>
	<div class="field">
		<%= f.label :DesPhPlantas, "Desviación estandar del Ph requerido por las plantas" %><br />
		<%= f.text_field :DesPhPlantas, :title => 'Medida de tolerancia del valor de Ph optimo para el desarrollo de la planta <br /> Tipo: numérico  <br /> Unidades: [ph] <br /> Ej: 0.5' %>
	</div>
	<div class="field">
		<%= f.label :PesoUniCultivo, "Peso seco de una planta madura" %><br />
		<%= f.text_field :PesoUniCultivo, :title => 'Peso de la planta cuando termina su desarrollo<br /> Tipo: numérico  <br /> Unidades: [gr] <br /> Ej: 276.7' %>
	</div>
	<div class="field">
		<%= f.label :DesPesoUniCul, "Desviación estandar del peso seco de una planta madura" %><br />
		<%= f.text_field :DesPesoUniCul, :title => 'Margen del peso de la planta cuando termina su desarrollo<br /> Tipo: numérico  <br /> Unidades: [gr] <br /> Ej: 31.07' %>
	</div>
	<div class="field">
		<%= f.label :PesoUniCosecha, "Peso seco del total de la cosecha de una planta" %><br />
		<%= f.text_field :PesoUniCosecha, :title => 'Peso de la cosecha durante todo un periodo productivo<br /> Tipo: numérico  <br /> Unidades: [gr] <br /> Ej: 238.2' %>
	</div>
	<div class="field">
		<%= f.label :DesPesoUniCos, "Desviación estandar del peso seco de la cosecha de una planta" %><br />
		<%= f.text_field :DesPesoUniCos, :title => 'Margen del peso de la cosecha durante todo un periodo productivo<br /> Tipo: numérico  <br /> Unidades: [gr] <br /> Ej: 31.07' %>
	</div>
	<div class="field">
		<%= f.label :TiemVegetativo, "Tiempo en estado de crecimiento" %><br />
		<%= f.text_field :TiemVegetativo, :title => 'Tiempo que tarda el cultivo en desarrollarse hasta estado productivo<br /> Tipo: numérico  <br /> Unidades: [días] <br /> Ej: 55' %>
	</div>
	<div class="field">
		<%= f.label :TiemReproductivo, "Tiempo en estado de producción" %><br />
		<%= f.text_field :TiemReproductivo, :title => 'Tiempo que tarda la producción del cultivo, es decir la cosecha<br /> Tipo: numérico  <br /> Unidades: [días] <br /> Ej: 57' %>
	</div>
	<div class="field">
		<%= f.label :ProLumiPlanta, "Luminosidad promedio optima para el cultivo" %><br />
		<%= f.text_field :ProLumiPlanta, :title => 'Promedio de luminosidad para el optimo desarrollo del cultivo<br /> Tipo: numérico  <br /> Unidades: [horas-luz/año] <br /> Ej: 2500' %>
	</div>
	<div class="field">
		<%= f.label :DesLumiPlanta, "Desviación estandar de la Luminosidad optima" %><br />
		<%= f.text_field :DesLumiPlanta, :title => 'Tolerancia de la planta en cuanto a luminosidad para el optimo desarrollo del cultivo<br /> Tipo: numérico  <br /> Unidades: [horas-luz/año] <br /> Ej: 700' %>
	</div>
	<div class="field">
		<%= f.label :ProPreciPlanta, "Precipitacion promedio optima para el cultivo" %><br />
		<%= f.text_field :ProPreciPlanta, :title => 'precipitación promedio de la planta en cuanto  para el optimo desarrollo del cultivo<br /> Tipo: numérico  <br /> Unidades: [horas-luz/año] <br /> Ej: 1500' %>
	</div>
	<div class="field">
		<%= f.label :DesPreciPlanta, "Desviación estandar de la precipitacion optima" %><br />
		<%= f.text_field :DesPreciPlanta, :title => 'Desviación estandar de la planta en cuanto a precipitación para el optimo desarrollo del cultivo<br /> Tipo: numérico  <br /> Unidades: [horas-luz/año] <br /> Ej: 200' %>
	</div>
	<div class="field">
		<%= f.label :ProHumePlanta, "Humedad promedio optima para el cultivo" %><br />
		<%= f.text_field :ProHumePlanta, :title => 'Humedad promedio de la planta para el optimo desarrollo del cultivo<br /> Tipo: numérico  <br /> Unidades: [%] <br /> Ej: 75' %>
	</div>
	<div class="field">
		<%= f.label :DesHumePlanta, "Desviación estandar de la Humedad promedio optima" %><br />
		<%= f.text_field :DesHumePlanta, :title => 'Desviación estandar de la planta en cuanto a humedad para el optimo desarrollo del cultivo<br /> Tipo: numérico  <br /> Unidades: [%] <br /> Ej: 5' %>
	</div>
	<div class="field">
		<%= f.label :ProTempPlanta, "Temperatura promedio optima  para el cultivo" %><br />
		<%= f.text_field :ProTempPlanta, :title => 'Temperatura promedio de la planta para el optimo desarrollo del cultivo<br /> Tipo: numérico  <br /> Unidades: [%] <br /> Ej: 27.5' %>
	</div>
	<div class="field">
		<%= f.label :DesTempPlanta, "Desviación estandar de la Temperatura promedio optima" %><br />
		<%= f.text_field :DesTempPlanta, :title => 'Desviación estandar de la planta a temperatura para el optimo desarrollo del cultivo<br /> Tipo: numérico  <br /> Unidades: [%] <br /> Ej: 2.5' %>
	</div>
	<div class="actions">
		<%= f.submit "Registrar Cultivo", :class => "button"%>
	</div>
<% end %>

app/views/crops/_refresh.js.erb
<% if flash[:success] == true %>
	<% unless @current_action == 'index'%>
		<% if @current_action == 'show'%>
			$('#crop').html("<%= escape_javascript(render :partial => 'crop') %>");
		<% elsif @current_action == 'edit'%>
			$('#crop').html("<%= escape_javascript(render :partial => 'form') %>");
		<% else %>
			clear_form_elements($('#crop > form')[0]);
			$('#crops').html("<%= escape_javascript(render :partial => 'crops') %>");
		<% end %>
			main_crops();
	<% else %>
		$('#navigation').html("<%= escape_javascript(render :partial => "layouts/menu") %>");
		$('#navigation a').on('click', function() {
			ajaxContentRedirect(this.href);
			return false;
		});
		$('#menutd > li > a:first').unbind('click');
	<% end %>	
<% end %>

$('html, body').animate({scrollTop:0}, 'slow');
$('#notice').html('<%= flash[:notice].html_safe %>');
$('#notice').slideDown("fast").delay(2500).fadeOut("slow");
<% flash[:notice] = nil %>

app/views/crops/admin.html.erb
<% unless @mode == 'public' %>	
	<% if @crop.errors.any? %>
		<div id="error_explanation">
			<h2> <%= pluralize(@crop.errors.count, "error")%>, posibles causas:</h2>
			<ul>
				<% @crop.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>		
			</ul>	
		</div>
	<% end %>
	
	<h3><span></span>Cultivo</h3>
	<br/>
	<div id="crop">	
		<%= render :partial => "form" %>
	</div>
	
	<div class="separator"></div>
	
	<h3><span></span> Listado de cultivos</h3>
	<br/>
	<div id="crops">	
		<%= render :partial => "crops" %>
	</div>
<% end %>

<div class="cleaner"></div>

<% unless @mode == 'public' %>
	<script type="text/javascript">	
		function complete_jquery_data_tables_crops(data, textStatus, jqxhr){
			if(textStatus == 'success'){
				libraries['jquery_data_tables']	=true;
				ready_jquery_data_tables('tablaCultivos');
			}
		};
		function main_crops(){
			if(!libraries['jquery_ui']){
				$.getScript("/assets/jquery/jquery-ui-1.8.23.custom.min.js", complete_jquery_ui);
			}
			else{
				ready_jquery_ui();
			}
			if(!libraries['jquery_tools']){
				$.getScript("/assets/jquery/jquery.tools.min.js", complete_jquery_tools);
			}
			else{
				ready_jquery_tools();
			}
			if(!libraries['jquery_data_tables']){
				$.getScript("/assets/jquery/jquery.dataTables.min.js", complete_jquery_data_tables_crops);
			}
			else{
				ready_jquery_data_tables('tablaCultivos');
			}
			
		};
		
		$(document).ready(function () {
			main_crops();
			<%= render :file => "crops/_refresh.js.erb" %>
		});
		
	</script> 
<% end %>

app/views/crops/index.html.erb
<% if @crop.errors.any? %>
	<div id="error_explanation">
		<h2> <%= pluralize(@crop.errors.count, "error")%>, posibles causas:</h2>
		<ul>
			<% @crop.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>		
		</ul>	
	</div>
<% end %>

<h3><span></span>Cultivo</h3>
<br/>
<div id="crop">	
	<%= render :partial => "crop" %>
</div>
	
<div class="separator"></div>

<h3><span></span> Listado de cultivos</h3>
<br/>
<div id="crops">	
	<%= render :partial => "crops" %>
</div>

<div class="cleaner"></div>

<script type="text/javascript">	
	function complete_jquery_data_tables_crops(data, textStatus, jqxhr){
		if(textStatus == 'success'){
			libraries['jquery_data_tables']	=true;
			ready_jquery_data_tables('tablaCultivos');
		}
	};
	function main_crops(){
		if(!libraries['jquery_ui']){
			$.getScript("/assets/jquery/jquery-ui-1.8.23.custom.min.js", complete_jquery_ui);
		}
		else{
			ready_jquery_ui();
		}
		if(!libraries['jquery_data_tables']){
			$.getScript("/assets/jquery/jquery.dataTables.min.js", complete_jquery_data_tables_crops);
		}
		else{
			ready_jquery_data_tables('tablaCultivos');
		}
		
	};
	
	$(document).ready(function () {
		main_crops();
		<%= render :file => "crops/_refresh.js.erb" %>
	});
	
</script>