config/routes.rb
Ecogranja::Application.routes.draw do
  root :to => "home#index"
  
  match "login",  :to => "sessions#login_attempt"
  match "logout", :to => "sessions#logout"
  
  match '/home/agropedia'         => 'home#agropedia'
  match '/home/learning'          => 'home#learning'
  match '/home/farmsadmin'        => 'home#farmsadmin'
  match '/home/administration'    => 'home#administration'
  match '/home/decisionmaking'    => 'home#decisionmaking'
  match '/sessions/login_attempt' => 'sessions#login_attempt'
  match '/sessions/logout'        => 'sessions#logout'
  match '/articles/admin'         => 'articles#admin'
  match '/crops/admin'            => 'crops#admin'  
  
  resources :home, :users, :profiles, :sessions, :farms, :coordinates, :crops, :productions, :environments, :soil_improvements, :scenarios, :articles, :categories, :simulations 
  
  

end

app/models/scenario.rb
class Scenario < ActiveRecord::Base
  attr_accessible :name,
                  :description,
                  :farm_id,
                  :environment_id,
                  :production_id,
                  :soil_improvement_id,
                  :crop_id
                  
  
  validates :name,                :presence => true
  validates :description,         :presence => true
  validates :environment_id,      :presence => true
  validates :crop_id,             :presence => true
  validates :production_id,       :presence => true
  validates :soil_improvement_id, :presence => true
  
  belongs_to :farm
  belongs_to :environment
  belongs_to :production
  belongs_to :soil_improvement
  belongs_to :crop
  
end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController
  
  def index
    unless @mode == 'public'
      @scenario           = Scenario.new
      @crops              = Crop.order('name')
      if @mode == 'normal'
        @farms              = Farm.where("user_id = '?'", @current_user.id)
        @environments       = Environment.where("farm_id = '?'", @farms.first.id)
        @productions        = Production.where("farm_id = '?'", @farms.first.id)
        @soil_improvements  = SoilImprovement.where("farm_id = '?'", @farms.first.id)
        @scenarios          = Scenario.where("farm_id = '?'", @farms.first.id)
      elsif @mode == 'admin'
        @farms              = Farm.order('name')
        @environments       = Environment.order('name')
        @productions        = Production.order('name')       
        @soil_improvements  = SoilImprovement.order('name')
        @scenarios          = Scenario.order('name')  
      end 
    end
    respond_to do |format|
      flash[:notice] = 'Administraci&oacute;n de Escenarios'
      flash[:success] = true
      format.html
    end
  end
  
  def create
    @scenario   = Scenario.new(params[:scenario])
    @crops              = Crop.order('name')
    if @mode == 'normal'
       @farms              = Farm.where("user_id = '?'", @current_user.id)
       @environments       = Environment.where("farm_id = '?'", @farms.first.id)
       @productions        = Production.where("farm_id = '?'", @farms.first.id)
       @soil_improvements  = SoilImprovement.where("farm_id = '?'", @farms.first.id)
       @scenarios          = Scenario.where("farm_id = '?'", @farms.first.id)
    elsif @mode == 'admin'
       @farms              = Farm.order('name')
       @environments       = Environment.order('name')
       @productions        = Production.order('name')       
       @soil_improvements  = SoilImprovement.order('name')
       @scenarios          = Scenario.order('name')  
    end
    respond_to do |format|
      if @scenario.save
        flash[:notice] = 'El escenario ha sido registrado satisfactoriamente.'
        flash[:success] = true
        format.js {
          render :partial => 'refresh'
        }
      else
        flash[:notice] = 'El escenario no ha sido registrado.'
        flash[:success] = false
        format.js {
          render :partial => 'refresh'
        }
      end
    end
  end
  
  def edit   
    @scenario           = Scenario.find(params[:id])
    @crops              = Crop.order('name')
    if @mode == 'normal'
       @farms              = Farm.where("user_id = '?'", @current_user.id)
       @environments       = Environment.where("farm_id = '?'", @farms.first.id)
       @productions        = Production.where("farm_id = '?'", @farms.first.id)
       @soil_improvements  = SoilImprovement.where("farm_id = '?'", @farms.first.id)
    elsif @mode == 'admin'
       @farms              = Farm.order('name')
       @environments       = Environment.order('name')
       @productions        = Production.order('name')       
       @soil_improvements  = SoilImprovement.order('name')
    end
    respond_to do |format|
      flash[:notice] = 'Edici&oacute;n del escenario: '+@scenario.name+'.'
      flash[:success] = true
      format.js {
        render :partial => 'refresh'
      } 
    end    
  end
  
  def update
    @scenario   = Scenario.find(params[:id])
    if @mode == 'normal'
      @farms         = Farm.where("user_id = '?'", @current_user.id)
      @scenarios          = Scenario.where("farm_id = '?'", @farms.first.id)
    elsif @mode == 'admin'
      @scenarios          = Scenario.order('name')
    end
    respond_to do |format|
      if @scenario.update_attributes(params[:scenario])
        flash[:notice] = 'El escenario ha sido actualizado satisfactoriamente'
        flash[:success] = true
        format.js {
          render :partial => 'refresh'
        } 
      else
        flash[:notice] = 'El escenario no ha sido actualizado'
        flash[:success] = false
        format.js {
          render :partial => 'refresh'
        }     
      end
    end
  end
  
  def destroy
    @scenario   = Scenario.find(params[:id])
    if @mode == 'normal'
      @farms              = Farm.where("user_id = '?'", @current_user.id)
      @scenarios          = Scenario.where("farm_id = '?'", @farms.first.id)
    elsif @mode == 'admin'
      @scenarios          = Scenario.order('name')
    end
    respond_to do |format|
      if @scenario.destroy
        flash[:notice] = 'El escenario fue eliminado satisfactoriamente'
        flash[:success] = true
        format.js { 
          render :partial => 'refresh'
        }
      else
        flash[:notice] = 'El escenario no fue eliminado'
        flash[:success] = false
        format.js { 
          render :partial => 'refresh'
        }
      end
    end
  end
  
end

app/helpers/scenarios_helper.rb
module ScenariosHelper
end

app/views/scenarios/_form.html.erb
<%= form_for(@scenario, :remote => true) do |f| %>	
	<div class="field">
		<%= f.label :name, "Nombre del escenario" %><br />
		<%= f.text_field :name, :title => 'Nombre del escenario de producción agropecuaria<br /> Tipo: alfanumérico <br /> Ej: Alta producción.' %>
	</div>
	<div class="field">
		<%= f.label :description, "Descripción del escenario" %><br />
		<%= f.text_field :description, :title => 'Descripción <br /> Tipo: alfabético <br /> Ej: Escenario que agrupa las condiciones para una producción intensiva' %>
	</div>
	<div class="field">
		<%= f.label  :farm_id, "Granja" %><br />
		<%= f.select :farm_id, @farms.collect {|c| [ c.name, c.id ]}, :title => 'Granja seleccionada' %>
	</div>
	<div class="field">
		<%= f.label  :environment_id, "Ambiente" %><br />
		<%= f.select :environment_id, @environments.collect {|c| [ c.name, c.id ]}, :title => 'Ambiente seleccionado' %>
	</div>
	<div class="field">
		<%= f.label  :production_id, "Producción" %><br />
		<%= f.select :production_id, @productions.collect {|c| [ c.name, c.id ]}, :title => 'Producción seleccionada' %>
	</div>
	<div class="field">
		<%= f.label  :soil_improvement_id, "Mejoramiento de suelo" %><br />
		<%= f.select :soil_improvement_id, @soil_improvements.collect {|c| [ c.name, c.id ]}, :title => 'Mejoramiento de suelo seleccionado' %>
	</div>
	<div class="field">
		<%= f.label  :crop_id, "Cultivo" %><br />
		<%= f.select :crop_id, @crops.collect {|c| [ c.name, c.id ]}, :title => 'Cultivos disponibles' %>
	</div>
	<div class="actions">
		<%= f.submit "Registrar Producción", :class => "button"%>
	</div>
<% end %>

app/views/scenarios/_refresh.js.erb
<% if flash[:success] == true %>
	<% unless @current_action == 'index'%>
		<% if @current_action == 'edit'%>
			$('#scenario').html("<%= escape_javascript(render :partial => 'form') %>");
		<% else %>
			clear_form_elements($('#scenario > form')[0])
			$('#scenarios').html("<%= escape_javascript(render :partial => 'scenarios') %>");
		<% end %>
			main_scenarios();
	<% else %>
		$('#navigation').html("<%= escape_javascript(render :partial => "layouts/menu") %>");
		$('#navigation a').on('click', function() {
			ajaxContentRedirect(this.href);
			return false;
		});
		$('#menutd > li > a:first').unbind('click');
	<% end %>	
<% end %>

$('html, body').animate({scrollTop:0}, 'slow');
$('#notice').html('<%= flash[:notice].html_safe %>');
$('#notice').slideDown("fast").delay(2500).fadeOut("slow");
<% flash[:notice] = nil %>

app/views/scenarios/_scenarios.html.erb
<table id="tablaEscenarios">
<thead>
<tr>
  <th>Nombre del escenario</th>
  <th>Descripción del escenario</th>
  <th>Granja</th>
  <th>Ambiente</th>
  <th>Producción</th>
  <th>Mejoramiento del suelo</th>
  <th>Cultivo</th>
  <th>Editar</th>
  <th>Eliminar</th>
</tr>
</thead>
<tbody>	
	<% @scenarios.each do |scenario| %>
	<tr>
	  <td><b> <%= scenario.name 					%></b></td>
	  <td>	  <%= scenario.description 				%></td>
	  <td>	  <%= scenario.farm.name 				%></td>
	  <td>	  <%= scenario.environment.name 		%></td>
	  <td>	  <%= scenario.production.name 			%></td>
	  <td>	  <%= scenario.soil_improvement.name	%></td>
	  <td>	  <%= scenario.crop.name 				%></td>
	  <td>	  <%= link_to 'Editar', edit_scenario_path(scenario), :method => "get", :remote => true, :class => "button" %></td>
	  <td>	  <%= button_to "Eliminar", scenario, :method => :delete, :remote => true, :class => "button" %></td>
	  
	</tr>
	<% end %>
</tbody>
</table>

<br />
<%= link_to 'Nuevo Escenario', { :controller => "scenarios", :action => "index"}, :class => "button" %>

app/views/scenarios/index.html.erb
<% unless @mode == 'public' %>	
	<% if @scenario.errors.any? %>
		<div id="error_explanation">
			<h2> <%= pluralize(@scenario.errors.count, "error")%>, posibles causas:</h2>
			<ul>
				<% @scenario.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>		
			</ul>	
		</div>
	<% end %>
	
	<h3><span></span>Escenario</h3>
	<br/>
	<div id="scenario">	
		<%= render :partial => "form" %>
	</div>
	
	<div class="separator"></div>
	
	<h3><span></span> Listado de escenarios</h3>
	<br/>
	<div id="scenarios">	
		<%= render :partial => "scenarios" %>
	</div>

<% end %>

<div class="cleaner"></div>

<% unless @mode == 'public' %>
	<script type="text/javascript">	
		function complete_jquery_data_tables_scenarios(data, textStatus, jqxhr){
			if(textStatus == 'success'){
				libraries['jquery_data_tables']	=true;
				ready_jquery_data_tables('tablaEscenarios');
			}
		};
		function main_scenarios(){
			if(!libraries['jquery_ui']){
				$.getScript("/assets/jquery/jquery-ui-1.8.23.custom.min.js", complete_jquery_ui);
			}
			else{
				ready_jquery_ui();
			}
			if(!libraries['jquery_tools']){
				$.getScript("/assets/jquery/jquery.tools.min.js", complete_jquery_tools);
			}
			else{
				ready_jquery_tools();
			}
			if(!libraries['jquery_data_tables']){
				$.getScript("/assets/jquery/jquery.dataTables.min.js", complete_jquery_data_tables_scenarios);
			}
			else{
				ready_jquery_data_tables('tablaEscenarios');
			}
			
		};
		
		$(document).ready(function () {
			main_scenarios();
			<%= render :file => "scenarios/_refresh.js.erb" %>
		});
		
	</script> 
<% end %>