config/routes.rb
Ecogranja::Application.routes.draw do
  root :to => "home#index"
  
  match "login",  :to => "sessions#login_attempt"
  match "logout", :to => "sessions#logout"
  
  match '/home/agropedia'         => 'home#agropedia'
  match '/home/learning'          => 'home#learning'
  match '/home/farmsadmin'        => 'home#farmsadmin'
  match '/home/administration'    => 'home#administration'
  match '/home/decisionmaking'    => 'home#decisionmaking'
  match '/sessions/login_attempt' => 'sessions#login_attempt'
  match '/sessions/logout'        => 'sessions#logout'
  match '/articles/admin'         => 'articles#admin'
  match '/crops/admin'            => 'crops#admin'  
  
  resources :home, :users, :profiles, :sessions, :farms, :coordinates, :crops, :productions, :environments, :soil_improvements, :scenarios, :articles, :categories, :simulations 
  
  

end

app/models/category.rb
class Category < ActiveRecord::Base
    attr_accessible :name, 
                    :description
                    
    validates :name,        :presence => true
    validates :description, :presence => true
    
    has_many :articles, :dependent => :destroy
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def index
    @category = Category.new
    @categories = Category.order('name')
    respond_to do |format|
      format.html 
    end
  end
  
  def create
    @category = Category.new(params[:category])
    respond_to do |format|
      if @category.save
        format.html {
          flash[:notice] = 'La categor&iacute;a ha sido registrada.'    
        }
      else
        format.html { 
          flash[:notice] = 'La categor&iacute;a no ha sido registrada.'  
        }
      end
      redirect_to :action => "index"
    end
  end
  
  def edit
    @category = Category.find(params[:id])
    @categories = Category.order('name')
    respond_to do |format|
        format.html { 
          render :action => "index" 
        }
    end
  end
  
  def update
    @category = Category.find(params[:id])
    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html {
          flash[:notice] = 'la categor&iacute;a fue actualizada satisfactoriamente' 
          redirect_to :action => "index" 
        } 
      else
        format.html {
          flash[:notice] = 'la categor&iacute;a no fue actualizada' 
          render action: "edit"
        }    
      end
    end
  end
  
  def destroy
    @category = Category.find(params[:id])
    respond_to do |format|
      if @category.delete
        format.html {
          flash[:notice] = 'la categor&iacute;a fue eliminada satisfactoriamente.' 
        }
      else  
        format.html { 
          flash[:notice] = 'la categor&iacute;a no fue eliminada.'
        }
      end
      redirect_to :action => "index"
    end
  end
  
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_categories.html.erb
<%unless defined? mode
	mode = 'normal'
  end %>
<table id="tablaCategorias">
<thead>
	<tr>
	  <th>Nombre</th>
	  <th>Descripción</th>
	  <% if mode.eql? 'admin' %>
		  <th>Editar</th>
		  <th>Eliminar</th>
	  <% end %>
	</tr>
</thead>
<tbody>
	<%if @categories.empty? %>
		<tr>
			<td colspan="4"><h3> No se encontraron registros.</h3></td>
		</tr>
	<%end%>
	
	<% @categories.each do |category| %>
	<tr>
	  <td><b><%= category.name %></b></td>
	  <td><%= category.description %></td>
	  <% if mode.eql? 'admin' %>
		  <td><%= link_to 'Editar', edit_category_path(category), :class => "button" %></td>
		  <td><%= button_to "Eliminar", category, :method => :delete %></td>
	  <% end %>
	</tr>
	<% end %>
</tbody>
</table>
 
<br />
<% if mode.eql? 'admin' %>
	<%= link_to 'Nueva categoría', { :controller => "categories", :action => "index"}, :class => "button" %>
<% end %>
<script type="text/javascript">
    $(document).ready(function () {
        $("a.button").button();
        
        <%if @categories.any? %>
        $("#tablaCategorias").dataTable({
        	"bJQueryUI": true,
        	"iDisplayLength": 4,
			"sPaginationType": "full_numbers",
			"sScrollX": "940px",
        	"bScrollCollapse": true,
			"oLanguage": {
			    "sUrl": "/assets/jquery/dataTables.spanish"
			}
        });
        <% end %>
    });
</script> 

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %>, posibles causas:</h2>
 
      <ul>
	      <% @acategory.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :name, "Nombre"%><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description, "Descripción"%><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit "Guardar categoría" %>
  </div>
<% end %>

<script type="text/javascript">
    $(document).ready(function () {
    	$("form").bind("keypress", function(e) {
            if (e.keyCode == 13) return false;
      	});
        $(".field label").addClass("ui-state-default ui-corner-all");
        $(".field input").addClass("ui-widget-content");
        $("input[type=submit]").button();
    });
</script> 

app/views/categories/index.html.erb
<% if flash[:notice] %>
<div id="notice">
	<p> <b>Noticia: </b><%= flash[:notice].html_safe %></p>
</div>  
<% end %>

<h3><span></span> Nueva categoría</h3>
<br/>
<div id="category_form" class="center">
	<%= render 'form' %>
</div>

<div class="separator"></div>

<h3><span></span> Listado de categorias</h3>
<br/>
<div id="categories">	
	<%= render :partial => "categories", :locals => {:mode => 'admin'} %>
</div>